'use strict';
const preferenceDefaults=()=>({keywords:[],languages:[],keepUnknown:true,volumeKeys:false,autoInterval:5,keepScreenOn:true,preload:3,doubleTap:true,longPress:false,pureBlack:false,highRefresh:false,startupUpdate:false,parallel:3,cacheLimit:500,downloadDir:'应用私有目录',picaSearchSort:'新到旧',picaFavoriteSort:'新到旧',avatarFrame:true,picaCheckIn:false,ehOriginal:false,ehIgnoreWarning:false,ehSubtitle:false,jmAutoDomain:true,jmFavoriteSort:'最新收藏',jmCheckIn:false,hitomiCdn:'gold-usergeneratedcontent.net',htDomain:'www.wnacg.com'});
const preferenceChoices={autoInterval:[2,3,5,10,15,30,60],preload:[1,2,3,4,5,6,7,8,9,10],parallel:[1,2,3,4,5,6],cacheLimit:[250,500,1000,2000],picaSearchSort:['新到旧','旧到新','最多喜欢'],picaFavoriteSort:['新到旧','旧到新'],jmFavoriteSort:['最新收藏','最早收藏','最近更新'],downloadDir:['应用私有目录','Documents/PiComic','SD 卡/PiComic']};
let settingsSource='picacg',cacheUsed=222.18,importCandidate=null,settingsScroll=new Map(),autoTurnTimer=null,autoTurning=false,readerInteracting=false,autoNextAt=0;
const webdavDraft={url:'',user:'',password:'',status:'尚未配置',connected:false,log:[],generation:0};
const prefs=()=>state.preferences;
function preference(key){return prefs()[key];}
function settingGroup(title,body){return `<section class="pref-group"><h3>${title}</h3><div class="pref-card">${body}</div></section>`;}
function prefRow(i,title,sub,action,value='',end=''){return `<button class="pref-row" data-action="${action}" data-value="${esc(value)}">${icon(i)}<span class="pref-copy"><strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</span><span class="pref-end">${end||icon('next')}</span></button>`;}
function prefToggle(key,title,sub='',disabled=false){return `<button class="pref-row pref-toggle" role="switch" aria-label="${title}" aria-checked="${!!preference(key)}" data-action="pref-toggle" data-value="${key}" ${disabled?'disabled':''}><span class="pref-copy"><strong>${title}</strong>${sub?`<small>${sub}</small>`:''}</span><span class="switch ${preference(key)?'on':''}" aria-hidden="true"></span></button>`;}
function prefChoice(key,title,sub='',unit=''){return prefRow('settings',title,sub,'pref-choice',key,`<span>${esc(preference(key))}${unit}</span>${icon('down')}`);}
function prefPage(title,body){return `${header(title)}<main class="page-body preferences-page">${body}</main>`;}
function languageSummary(){return prefs().languages.length?prefs().languages.join('、'):'不限语言';}
function renderSettings(){return prefPage('设置',`<p class="settings-intro">阅读、内容与应用偏好</p>${settingGroup('内容与来源',prefRow('user','账号管理','登录方式、会话与账号资料','navigate','accounts')+prefRow('grid','漫画源','六个平台的专属配置','navigate','source-settings')+prefRow('filter','内容筛选',`关键词屏蔽 ${prefs().keywords.length} 项 · ${languageSummary()}`,'navigate','content-settings'))}${settingGroup('阅读体验',prefRow('book','阅读',`${{ltr:'从左向右',rtl:'从右向左',scroll:'纵向连续'}[state.mode]} · 预加载 ${prefs().preload} 张`,'navigate','reading-settings')+prefRow('moon','外观',`${state.theme==='dark'?'深色模式':'浅色模式'} · ${prefs().highRefresh?'优先高刷新率':'跟随系统刷新率'}`,'navigate','appearance-settings'))}${settingGroup('APP',prefRow('refresh','更新','GitHub Releases · 检查更新与启动检测','navigate','updates')+prefRow('database','数据与同步',`缓存 ${cacheUsed.toFixed(2)} MB / ${prefs().cacheLimit} MB · WebDAV`,'navigate','data-settings')+prefRow('log','日志','查看与导出诊断记录','navigate','logs'))}${settingGroup('网络与关于',prefRow('wifi','设置代理',state.network==='system'?'跟随系统网络 / VPN':'自定义 HTTP 代理','navigate','network')+prefRow('info','关于 PiComic','项目地址与问题反馈','navigate','about-page'))}<p class="pref-footnote">PiComic · 手机交互原型</p>`);}
function renderContentSettings(){return prefPage('内容筛选',`${settingGroup('关键词屏蔽',`<p class="pref-description">匹配标题、作者和标签。多个关键词命中任意一项即隐藏，不影响本地书架与下载。</p><div class="keyword-list">${prefs().keywords.length?prefs().keywords.map((k,i)=>`<span class="keyword-tag">${esc(k)}<button aria-label="移除关键词 ${esc(k)}" data-action="keyword-remove" data-value="${i}">${icon('close')}</button></span>`).join(''):'<span class="muted">尚未添加屏蔽词</span>'}</div>${prefRow('plus','添加关键词','可一次添加多个，每行一个','keyword-add')}`)}${settingGroup('语言筛选',`<p class="pref-description">可多选；全部取消表示不限语言。</p>${['Chinese','English','Japanese'].map(l=>`<button class="pref-row" role="checkbox" aria-checked="${prefs().languages.includes(l)}" data-action="language-toggle" data-value="${l}"><span class="pref-copy"><strong>${l}</strong></span><span class="pref-checkbox ${prefs().languages.includes(l)?'checked':''}">${prefs().languages.includes(l)?icon('check'):''}</span></button>`).join('')}${prefToggle('keepUnknown','保留未标注语言的作品','只有选择语言筛选时生效')}`)}<div class="notice">${icon('info')}<span>以上筛选应用于探索、搜索及分类结果；来源不提供语言数据时，按“未标注”处理。</span></div>`);}
function renderReadingSettings(){return prefPage('阅读',`${settingGroup('翻页',prefRow('book','阅读模式',({ltr:'从左向右',rtl:'从右向左',scroll:'纵向连续'})[state.mode],'reading-mode-sheet')+prefToggle('volumeKeys','音量键翻页','音量减：下一页；音量加：上一页')+prefChoice('autoInterval','自动翻页时间间隔','在阅读器中手动开启自动翻页',' 秒'))}${settingGroup('画面与加载',prefToggle('keepScreenOn','保持屏幕常亮','仅在前台阅读时生效')+prefChoice('preload','图片预加载','沿阅读方向提前加载，受内存和来源额度限制',' 张'))}${settingGroup('手势',prefToggle('doubleTap','双击缩放','双击放大，再次双击恢复')+prefToggle('longPress','长按缩放','按住临时放大，松开恢复'))}<p class="pref-footnote">音量键、常亮和真实图片预加载在 Android 中实现。</p>`);}
function renderAppearanceSettings(){return prefPage('外观',`${settingGroup('主题',`<button class="pref-row" role="switch" aria-label="深色模式" aria-checked="${state.theme==='dark'}" data-action="theme"><span class="pref-copy"><strong>深色模式</strong><small>使用适合夜间阅读的深色界面</small></span><span class="switch ${state.theme==='dark'?'on':''}" aria-hidden="true"></span></button>${prefToggle('pureBlack','纯黑色模式','深色模式下使用纯黑背景',state.theme!=='dark')}`)}${settingGroup('显示',prefToggle('highRefresh','高刷新率模式','优先使用设备支持的较高刷新率'))}<div class="theme-sample"><div></div><strong>${state.theme==='dark'?(prefs().pureBlack?'纯黑主题':'深色主题'):'浅色主题'}</strong><span>界面预览</span></div><p class="pref-footnote">高刷新率受硬件、系统和省电策略限制，原型仅保存偏好。</p>`);}
function sourceLineRow(type,title){const value=(state.lines[settingsSource]||{api:1,image:1})[type];return prefRow(type==='api'?'globe':'grid',title,'','source-line',type,`<span>分流 ${value}</span>${icon('down')}`);}
function renderSourceSettings(){
  let body='';
  if(settingsSource==='picacg')body=settingGroup('picacg',prefChoice('picaSearchSort','搜索及分类排序模式')+prefChoice('picaFavoriteSort','收藏夹漫画排序模式')+prefToggle('avatarFrame','显示头像框')+prefToggle('picaCheckIn','自动打卡','启动时检查，当日尚未打卡才执行'));
  else if(settingsSource==='ehentai')body=settingGroup('E-Hentai',prefRow('globe','画廊站点','EX 访问权限单独验证','source-eh-site','',`<span>${state.ehSite==='EX'?'exhentai.org':'e-hentai.org'}</span>${icon('down')}`)+prefToggle('ehOriginal','优先加载原图','可能增加流量，或因额度与权限加载失败')+prefToggle('ehIgnoreWarning','忽略警告','仅指站内内容提示，不包含网络安全或权限错误')+prefToggle('ehSubtitle','优先显示副标题','适用于已下载的画廊')+prefRow('log','配置文件','编辑此平台的设置','eh-config'));
  else if(settingsSource==='nhentai')body=settingGroup('nhentai',prefRow('trash','删除 Cookie','清除网页会话，API Key 单独保留','delete-nh-cookie'));
  else if(settingsSource==='jmcomic')body=settingGroup('禁漫天堂',prefToggle('jmAutoDomain','自动选择域名','登录时选择可用的 API 域名')+sourceLineRow('api','API 域名')+sourceLineRow('image','图片分流')+prefChoice('jmFavoriteSort','收藏夹漫画排序模式')+prefRow('refresh','更新 API 域名','重新获取平台的候选线路','refresh-jm-domains')+prefToggle('jmCheckIn','自动签到','当日未签到且会话有效时执行')+prefRow('check','测试签到','仅模拟，不发送真实请求','simulate-checkin'));
  else if(settingsSource==='hitomi')body=settingGroup('Hitomi',prefRow('globe','CDN 域名',esc(prefs().hitomiCdn),'edit-domain','hitomiCdn',icon('edit')));
  else body=settingGroup('绅士漫画',prefRow('globe','域名',esc(prefs().htDomain),'edit-domain','htDomain',icon('edit')));
  return `${header('漫画源')}<div class="source-pref-tabs" role="tablist" aria-label="漫画源配置">${sources.map(s=>`<button class="platform-tab ${settingsSource===s.id?'selected':''}" role="tab" aria-selected="${settingsSource===s.id}" data-action="settings-source" data-value="${s.id}">${platformNames[s.id]}</button>`).join('')}</div><main class="page-body preferences-page">${body}<p class="pref-footnote">平台参数来自参考界面，地址尚未实测。修改仅影响演示配置。</p></main>`;
}
function renderDataSettings(){return prefPage('数据与同步',`${settingGroup('下载偏好',prefChoice('downloadDir','设置下载目录','目录选择在原型中演示')+prefChoice('parallel','下载并行','同时执行的章节任务上限',' 个'))}${settingGroup('缓存',`<div class="cache-meter"><span>已使用 <strong>${cacheUsed.toFixed(2)} MB</strong></span><span>上限 ${prefs().cacheLimit} MB</span><progress max="${prefs().cacheLimit}" value="${Math.min(cacheUsed,prefs().cacheLimit)}" aria-label="缓存使用量"></progress></div>${prefChoice('cacheLimit','缓存大小限制','临时图片缓存，不包含已下载漫画',' MB')}${prefRow('trash','清除缓存',`${cacheUsed.toFixed(2)} MB · 保留书架、账号与下载`,'clear-cache')}`)}${settingGroup('用户数据',prefRow('download','导出用户数据','书架、历史及阅读偏好 · JSON','export-data')+prefRow('upload','导入用户数据','校验文件并预览后合并','import-data')+prefRow('cloud','数据同步 WebDAV',webdavDraft.status,'navigate','webdav'))}<input id="backup-input" type="file" accept=".json,application/json" hidden><p class="pref-footnote">备份不包含账号凭据、下载文件和设备专属目录。</p>`);}
function renderWebdav(){return prefPage('WebDAV 同步',`<p class="pref-description">同步书架、阅读进度与偏好。首次同步先预览差异，不覆盖未确认的数据。</p><form id="webdav-form" class="pref-form"><label for="dav-url">服务器地址</label><input id="dav-url" type="url" placeholder="https://dav.example.com/PiComic/" value="${esc(webdavDraft.url)}" required><label for="dav-user">用户名</label><input id="dav-user" value="${esc(webdavDraft.user)}" autocomplete="off"><label for="dav-password">密码 / 应用密码</label><input id="dav-password" type="password" value="${esc(webdavDraft.password)}" autocomplete="off"><button class="secondary-button full-width" type="submit">模拟测试连接</button></form><p class="dav-status" role="status">${webdavDraft.status}</p><button class="primary-button full-width" data-action="dav-sync" ${webdavDraft.connected?'':'disabled'}>${icon('cloud')}预览同步</button><p class="pref-footnote">离线演示，不连接服务器。地址与凭据仅留在本次表单内，不持久化或导出。</p>`);}
function renderLogs(){return prefPage('日志',`<p class="pref-description">最近的运行记录，敏感字段已排除。</p><div class="log-list"><p><time>09:41:00</time><strong>INFO</strong> 启动 PiComic 原型</p><p><time>09:41:01</time><strong>INFO</strong> 加载本地设置</p><p><time>09:41:02</time><strong>INFO</strong> 演示数据就绪</p></div>${prefRow('upload','导出日志','仅导出以上示例，不含账号与网址','export-logs')}<p class="pref-footnote">这是示例日志，不是 Android 运行记录。</p>`);}
function renderAbout(){return prefPage('关于 PiComic',`<div class="about-brand"><img src="assets/icon.svg" alt="PiComic logo"><h1>PiComic</h1><span>每一页，都值得慢慢读。</span><p>面向 Android 手机的多平台漫画阅读器，专注于发现、收藏与阅读。</p></div>${settingGroup('项目',prefRow('globe','项目地址','GitHub 仓库待配置','project-link')+prefRow('info','问题反馈','GitHub Issues · 仓库待配置','feedback-link'))}<button class="text-button full-width" data-action="reset">重置演示状态</button>`);}
function renderSettingsRoute(){return ({'content-settings':renderContentSettings,'source-settings':renderSourceSettings,'reading-settings':renderReadingSettings,'appearance-settings':renderAppearanceSettings,'data-settings':renderDataSettings,webdav:renderWebdav,logs:renderLogs,'about-page':renderAbout}[route])?.();}
function applyPreference(key,value){if(!Object.hasOwn(preferenceDefaults(),key))return;prefs()[key]=value;persist();render();}
function choosePreference(key){const options=preferenceChoices[key];if(!options)return;sheet('选择设置',`<div class="preference-options" role="radiogroup">${options.map(v=>`<button class="radio-row ${preference(key)===v?'selected':''}" role="radio" aria-checked="${preference(key)===v}" data-action="pref-select" data-key="${key}" data-value="${esc(v)}"><span class="radio-dot"></span>${esc(v)}${{autoInterval:' 秒',preload:' 张',parallel:' 个',cacheLimit:' MB'}[key]||''}</button>`).join('')}</div>`);}
function visibleBook(b){const p=prefs(),text=`${b.title} ${b.author} ${b.category}`.normalize('NFKC').toLowerCase();if(p.keywords.some(k=>text.includes(k.normalize('NFKC').toLowerCase())))return false;const lang=b.language;return !p.languages.length||(lang?p.languages.includes(lang):p.keepUnknown);}
function filteredBooks(list){return list.filter(visibleBook);}
function stopAutoTurn(){clearInterval(autoTurnTimer);autoTurnTimer=null;autoTurning=false;}
function resetAutoCountdown(){autoNextAt=Date.now()+prefs().autoInterval*1000;}
function toggleAutoTurn(){
 if(autoTurning){stopAutoTurn();renderReader();return;}
 autoTurning=true;resetAutoCountdown();
 autoTurnTimer=setInterval(()=>{
  if(route!=='reader'||document.hidden){stopAutoTurn();return;}
  if(scenario!=='normal'){stopAutoTurn();renderReader();return;}
  if($('.sheet')||zoom>1||readerInteracting){resetAutoCountdown();return;}
  if(Date.now()<autoNextAt)return;
  if(page>=book().pages){stopAutoTurn();renderReader();toast('本章已结束，自动翻页已停止');return;}
  setPage(page+1);
 },100);renderReader();
}
function safeBackup(){return {app:'PiComicPrototype',schemaVersion:1,exportedAt:new Date().toISOString(),favorites:[...state.favorites],history:structuredClone(state.history),preferences:{keywords:[...prefs().keywords],languages:[...prefs().languages],keepUnknown:prefs().keepUnknown,autoInterval:prefs().autoInterval,preload:prefs().preload,doubleTap:prefs().doubleTap,longPress:prefs().longPress},mode:state.mode,theme:state.theme};}
function downloadText(name,text,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function validateBackup(data){
  if(!data||data.app!=='PiComicPrototype'||data.schemaVersion!==1||!Array.isArray(data.favorites)||!data.history||typeof data.history!=='object'||Array.isArray(data.history))throw Error('文件格式或版本不支持');
  const validKey=k=>typeof k==='string'&&sources.some(s=>books.some(b=>k===s.id+':'+b.id));
  if(data.favorites.length>10000||data.favorites.some(k=>typeof k!=='string'||!validKey(k)))throw Error('书架记录不合法');
  const candidate={favorites:[...new Set(data.favorites)],history:{},preferences:{}};
  for(const [k,h] of Object.entries(data.history)){if(!validKey(k)||!h||!Number.isInteger(h.page)||h.page<1||!Number.isInteger(h.chapter)||h.chapter<1||!Number.isFinite(h.time))throw Error('阅读记录不合法');const b=books.find(b=>k.endsWith(':'+b.id));if(h.page>b.pages||h.chapter>b.chapters)throw Error('页码或章节超出范围');candidate.history[k]={page:h.page,chapter:h.chapter,time:h.time};}
  const p=data.preferences||{};
  if(p.keywords!==undefined){if(!Array.isArray(p.keywords)||p.keywords.length>100||p.keywords.some(k=>typeof k!=='string'||!k.trim()||k.length>80))throw Error('屏蔽词不合法');candidate.preferences.keywords=[...new Set(p.keywords)];}
  if(p.languages!==undefined){if(!Array.isArray(p.languages)||p.languages.some(l=>!['Chinese','English','Japanese'].includes(l)))throw Error('语言设置不合法');candidate.preferences.languages=[...new Set(p.languages)];}
  for(const k of ['keepUnknown','doubleTap','longPress'])if(p[k]!==undefined){if(typeof p[k]!=='boolean')throw Error('开关设置不合法');candidate.preferences[k]=p[k];}
  for(const k of ['autoInterval','preload'])if(p[k]!==undefined){if(!preferenceChoices[k].includes(p[k]))throw Error('阅读设置超出范围');candidate.preferences[k]=p[k];}
  if(['ltr','rtl','scroll'].includes(data.mode))candidate.mode=data.mode;if(['light','dark'].includes(data.theme))candidate.theme=data.theme;
  return candidate;
}
async function previewImport(file){try{if(!file)return;if(file.size>1024*1024)throw Error('文件超过 1 MB');importCandidate=validateBackup(JSON.parse(await file.text()));sheet('导入用户数据',`<p class="sheet-sub">文件校验通过：${importCandidate.favorites.length} 部收藏、${Object.keys(importCandidate.history).length} 条历史。书架合并去重，历史保留较新记录，导入的阅读偏好将应用。</p><div class="sheet-footer"><button class="secondary-button" data-action="close">取消</button><button class="primary-button" data-action="confirm-import">确认合并</button></div>`);}catch(e){importCandidate=null;toast('导入失败：'+e.message);}}
function startupUpdateDemo(){if(!prefs().startupUpdate)return;let last=0;try{last=Number(localStorage.getItem('picomic-startup-check')||0);}catch{}if(Date.now()-last<86400000)return;try{localStorage.setItem('picomic-startup-check',Date.now());}catch{}setTimeout(()=>toast('启动检查：发现新版本 1.1.0（模拟），可在更新页查看'),700);}
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,v=el.dataset.value;
  if(a==='pref-toggle')applyPreference(v,!preference(v));
  else if(a==='pref-choice')choosePreference(v);
  else if(a==='pref-select'){const options=preferenceChoices[el.dataset.key],value=options?.find(x=>String(x)===v);if(value!==undefined){closeSheet(false);applyPreference(el.dataset.key,value);}}
  else if(a==='keyword-add')sheet('添加屏蔽关键词',`<form id="keyword-form" class="pref-form"><label for="keyword-input">每行一个关键词</label><textarea id="keyword-input" rows="4" maxlength="8000" placeholder="例如：雨后&#10;某位作者" required></textarea><button class="primary-button full-width" type="submit">添加</button></form>`);
  else if(a==='keyword-remove'){prefs().keywords.splice(Number(v),1);persist();render();}
  else if(a==='language-toggle'){prefs().languages=prefs().languages.includes(v)?prefs().languages.filter(l=>l!==v):[...prefs().languages,v];persist();render();}
  else if(a==='reading-mode-sheet')sheet('阅读模式',modeOptions());
  else if(a==='settings-source'){settingsSource=v;render();}
  else if(a==='source-eh-site')sheet('画廊站点',['EH','EX'].map(site=>`<button class="radio-row ${state.ehSite===site?'selected':''}" data-action="source-select-eh" data-value="${site}"><span class="radio-dot"></span>${site==='EH'?'e-hentai.org':'exhentai.org'}</button>`).join(''));
  else if(a==='source-select-eh'){state.ehSite=v;persist();closeSheet(false);render();}
  else if(a==='source-line')sheet(v==='api'?'API 域名':'图片分流',[1,2,3,4,5,6].map(n=>`<button class="radio-row" data-action="source-select-line" data-key="${v}" data-value="${n}"><span class="radio-dot"></span>分流 ${n} · 演示候选</button>`).join(''));
  else if(a==='source-select-line'){state.lines[settingsSource]={...(state.lines[settingsSource]||{api:1,image:1}),[el.dataset.key]:Number(v)};persist();closeSheet(false);render();}
  else if(a==='delete-nh-cookie')confirmSheet('删除 nhentai Cookie？','将退出此平台的网页会话。使用 API Key 的登录状态仍然保留。','confirm-delete-nh','');
  else if(a==='confirm-delete-nh'){if(accountInfo('nhentai')?.method!=='key')delete state.accounts.nhentai;persist();closeSheet(false);render();toast('已清除网页会话（模拟）');}
  else if(a==='refresh-jm-domains')sheet('更新 API 域名',`<p class="sheet-sub">模拟获得 6 条候选线路，当前线路保持不变。真实域名需平台验证。</p><button class="primary-button full-width" data-action="close">完成</button>`);
  else if(a==='simulate-checkin')toast(prefs().jmCheckIn?'模拟签到完成，今日不重复执行':'请先开启自动签到');
  else if(a==='edit-domain')sheet('编辑域名',`<form id="domain-form" data-key="${v}" class="pref-form"><label for="domain-input">仅填写主机名</label><input id="domain-input" value="${esc(preference(v))}" required><p class="outline-note">仅保存演示配置，不发送请求。</p><button class="primary-button full-width" type="submit">保存</button></form>`);
  else if(a==='eh-config')sheet('E-Hentai 配置文件',`<form id="eh-config-form" class="pref-form"><label for="eh-config-input">平台偏好 JSON</label><textarea id="eh-config-input" rows="7">${esc(JSON.stringify({site:state.ehSite,original:prefs().ehOriginal,ignoreWarning:prefs().ehIgnoreWarning,subtitle:prefs().ehSubtitle},null,2))}</textarea><button class="primary-button full-width" type="submit">保存配置</button></form>`);
  else if(a==='clear-cache')confirmSheet('清除缓存？',`将清除 ${cacheUsed.toFixed(2)} MB 演示临时缓存，下载、书架与账号不受影响。`,'confirm-cache','');
  else if(a==='confirm-cache'){cacheUsed=0;closeSheet(false);render();toast('缓存已清除（模拟）');}
  else if(a==='export-data'){downloadText('PiComic-user-data.json',JSON.stringify(safeBackup(),null,2));toast('已导出演示用户数据');}
  else if(a==='import-data')$('#backup-input').click();
  else if(a==='confirm-import'&&importCandidate){state.favorites=[...new Set([...state.favorites,...importCandidate.favorites])];for(const [k,h] of Object.entries(importCandidate.history))if(!state.history[k]||h.time>state.history[k].time)state.history[k]=h;Object.assign(prefs(),importCandidate.preferences);if(importCandidate.mode)state.mode=importCandidate.mode;if(importCandidate.theme)state.theme=importCandidate.theme;importCandidate=null;persist();closeSheet(false);render();toast('用户数据已合并');}
  else if(a==='export-logs')downloadText('PiComic-demo.log','09:41:00 INFO 启动 PiComic 原型\n09:41:01 INFO 加载本地设置\n09:41:02 INFO 演示数据就绪\n','text/plain');
  else if(a==='dav-sync'&&webdavDraft.connected)sheet('同步差异 · 演示',`<p class="sheet-sub">云端示例：新增 1 部收藏，1 条阅读进度冲突。选择冲突处理方式，当前不会发送网络请求。</p><button class="radio-row" data-action="dav-merge" data-value="local">保留本机进度并合并收藏</button><button class="radio-row" data-action="dav-merge" data-value="remote">采用云端示例进度并合并收藏</button><button class="text-button full-width" data-action="close">取消</button>`);
  else if(a==='dav-merge'){state.favorites=[...new Set([...state.favorites,'picacg:8'])];if(v==='remote')state.history['picacg:0']={page:8,chapter:1,time:Date.now()};persist();webdavDraft.status='模拟同步完成';closeSheet(false);render();toast('已合并云端示例数据，未发送网络请求');}
  else if(a==='project-link'||a==='feedback-link')sheet(a==='project-link'?'项目地址':'问题反馈',`<p class="sheet-sub">项目 GitHub 仓库尚未配置。正式版分别打开项目首页或 Issues 页面。</p><button class="primary-button full-width" data-action="close">了解了</button>`);
  else if(a==='auto-turn')toggleAutoTurn();
});
document.addEventListener('submit',e=>{
  const form=e.target;if(form.id==='keyword-form'){e.preventDefault();const words=$('#keyword-input').value.split(/\r?\n/).map(w=>w.trim()).filter(Boolean);if(words.some(w=>w.length>80)||prefs().keywords.length+words.length>100){toast('最多 100 项，每项不超过 80 个字符');return;}prefs().keywords=[...new Map([...prefs().keywords,...words].map(w=>[w.normalize('NFKC').toLowerCase(),w])).values()];persist();closeSheet(false);render();}
  else if(form.id==='domain-form'){e.preventDefault();const value=$('#domain-input').value.trim().toLowerCase();if(!/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(value)){toast('请输入有效主机名，不包含协议、路径或账号');return;}closeSheet(false);applyPreference(form.dataset.key,value);}
  else if(form.id==='eh-config-form'){e.preventDefault();try{const c=JSON.parse($('#eh-config-input').value);if(!['EH','EX'].includes(c.site)||['original','ignoreWarning','subtitle'].some(k=>typeof c[k]!=='boolean')||Object.keys(c).some(k=>!['site','original','ignoreWarning','subtitle'].includes(k)))throw Error();state.ehSite=c.site;Object.assign(prefs(),{ehOriginal:c.original,ehIgnoreWarning:c.ignoreWarning,ehSubtitle:c.subtitle});persist();closeSheet(false);render();}catch{toast('配置格式不正确，原设置未修改');}}
  else if(form.id==='webdav-form'){e.preventDefault();try{const url=new URL($('#dav-url').value);if(url.protocol!=='https:'||url.username||url.password)throw Error();webdavDraft.url=url.href;webdavDraft.user=$('#dav-user').value;webdavDraft.password=$('#dav-password').value;webdavDraft.connected=true;webdavDraft.status='模拟连接成功 · 尚未同步';render();}catch{webdavDraft.connected=false;webdavDraft.status='请输入 HTTPS 地址，不在网址中包含凭据';$('.dav-status').textContent=webdavDraft.status;$('[data-action="dav-sync"]').disabled=true;}}
});
document.addEventListener('change',e=>{if(e.target.id==='backup-input')previewImport(e.target.files[0]);});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAutoTurn();if(route==='reader')renderReader();}});

document.addEventListener('input',e=>{if(e.target.closest('#webdav-form')){webdavDraft.connected=false;$('[data-action="dav-sync"]').disabled=true;$('.dav-status').textContent='配置已修改，请重新测试连接';}});
